/* Three design directions, all within "clean industrial / engineering".
   Each is a set of CSS custom properties applied to the app root. */
(function () {
  const THEMES = {
    // 1) BLUEPRINT — cool technical drawing. Thin lines, mono labels, blueprint blue.
    blueprint: {
      label: { zh: "藍圖 Blueprint", en: "Blueprint" },
      blurb: { zh: "工程製圖風・冷灰底・細格線・藍圖藍", en: "Drafting feel · cool grey · hairlines · blueprint blue" },
      vars: {
        "--bg": "#eef1f4",
        "--surface": "#ffffff",
        "--surface-2": "#f6f8fa",
        "--line": "#d2dae2",
        "--line-strong": "#aebccb",
        "--ink": "#152232",
        "--ink-2": "#43566b",
        "--ink-3": "#7d8fa0",
        "--accent": "#1f5fbf",
        "--accent-ink": "#ffffff",
        "--accent-soft": "#e3edfb",
        "--ok": "#1f8a5b",
        "--warn": "#b06a12",
        "--radius": "4px",
        "--radius-lg": "6px",
        "--font": "'IBM Plex Sans','Helvetica Neue',Arial,'Noto Sans TC',sans-serif",
        "--mono": "'IBM Plex Mono','SFMono-Regular',ui-monospace,monospace",
        "--shadow": "0 1px 2px rgba(21,34,50,.06), 0 2px 8px rgba(21,34,50,.05)",
        "--shadow-lg": "0 8px 30px rgba(21,34,50,.12)",
        "--header-bg": "#152232",
        "--header-ink": "#eef3f9",
        "--header-accent": "#5f95e6",
        "--grid": "rgba(31,95,191,.06)",
        "--label-spacing": ".08em",
        "--label-transform": "uppercase",
      },
    },

    // 2) WORKSHOP — shop-floor. Dark slate, safety orange, big bold touch targets.
    workshop: {
      label: { zh: "工坊 Workshop", en: "Workshop" },
      blurb: { zh: "現場高對比・深石板・安全橘・大觸控", en: "Shop-floor contrast · dark slate · safety orange · big targets" },
      vars: {
        "--bg": "#15181c",
        "--surface": "#1f242b",
        "--surface-2": "#272d36",
        "--line": "#363d47",
        "--line-strong": "#4a525e",
        "--ink": "#f2f4f7",
        "--ink-2": "#aeb7c2",
        "--ink-3": "#7f8a97",
        "--accent": "#ff6a1a",
        "--accent-ink": "#1a1206",
        "--accent-soft": "#3a2414",
        "--ok": "#3fcf8e",
        "--warn": "#ffb020",
        "--radius": "8px",
        "--radius-lg": "12px",
        "--font": "'Inter','Helvetica Neue',Arial,'Noto Sans TC',sans-serif",
        "--mono": "'Roboto Mono',ui-monospace,monospace",
        "--shadow": "0 1px 2px rgba(0,0,0,.4), 0 2px 10px rgba(0,0,0,.35)",
        "--shadow-lg": "0 14px 40px rgba(0,0,0,.5)",
        "--header-bg": "#0f1216",
        "--header-ink": "#f2f4f7",
        "--header-accent": "#ff6a1a",
        "--grid": "rgba(255,255,255,.025)",
        "--label-spacing": ".04em",
        "--label-transform": "uppercase",
      },
    },

    // 3) DATASHEET — refined spec sheet. Warm paper, near-black ink, deep graphite-teal.
    datasheet: {
      label: { zh: "規格表 Datasheet", en: "Datasheet" },
      blurb: { zh: "精緻規格表・暖白紙・墨黑・留白", en: "Refined spec sheet · warm paper · ink black · whitespace" },
      vars: {
        "--bg": "#eceae4",
        "--surface": "#faf9f6",
        "--surface-2": "#f2f0ea",
        "--line": "#ded9cf",
        "--line-strong": "#c4bcab",
        "--ink": "#1c1b18",
        "--ink-2": "#5a564e",
        "--ink-3": "#8c8678",
        "--accent": "#0f6e63",
        "--accent-ink": "#ffffff",
        "--accent-soft": "#dcebe8",
        "--ok": "#2f7d4f",
        "--warn": "#9a6a1a",
        "--radius": "2px",
        "--radius-lg": "3px",
        "--font": "'Newsreader','Georgia',serif",
        "--body-font": "'IBM Plex Sans','Helvetica Neue',Arial,'Noto Sans TC',sans-serif",
        "--mono": "'IBM Plex Mono',ui-monospace,monospace",
        "--shadow": "0 1px 1px rgba(28,27,24,.04), 0 1px 6px rgba(28,27,24,.05)",
        "--shadow-lg": "0 10px 36px rgba(28,27,24,.12)",
        "--header-bg": "#1c1b18",
        "--header-ink": "#f4f2ec",
        "--header-accent": "#7fc8bd",
        "--grid": "rgba(15,110,99,.05)",
        "--label-spacing": ".14em",
        "--label-transform": "uppercase",
      },
    },
  };

  window.THEMES = THEMES;
})();
